{% set name = "pretty_midi" %}
{% set version = "0.2.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pretty_midi-{{ version }}.tar.gz
  sha256: ea6e192f94044674e833336ea1f415318ddf28e320302ac7b109edff0d4534bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mido
    - numpy >=1.7.0
    - python >=2.7
    - six

test:
  imports:
    - pretty_midi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/craffel/pretty-midi
  summary: Functions and classes for handling MIDI data conveniently.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Walter-0
